// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC10xxAzpPklDeYmwsIoqupWnhanDnjUhk',
    appId: '1:460507002308:web:0b9d61fb4d616fb2c4e091',
    messagingSenderId: '460507002308',
    projectId: 'energenius-56431',
    authDomain: 'energenius-56431.firebaseapp.com',
    storageBucket: 'energenius-56431.firebasestorage.app',
    measurementId: 'G-53D2Y4Y27N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq7MvoXK2AdHiA4Bv6hKAESYler2AxqBk',
    appId: '1:460507002308:android:5f414b279230779ac4e091',
    messagingSenderId: '460507002308',
    projectId: 'energenius-56431',
    storageBucket: 'energenius-56431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnRywfUPBFEakuL_QUgTIU9VGVYoRQMvk',
    appId: '1:460507002308:ios:5d76a137acf51c59c4e091',
    messagingSenderId: '460507002308',
    projectId: 'energenius-56431',
    storageBucket: 'energenius-56431.firebasestorage.app',
    iosBundleId: 'com.example.energenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnRywfUPBFEakuL_QUgTIU9VGVYoRQMvk',
    appId: '1:460507002308:ios:5d76a137acf51c59c4e091',
    messagingSenderId: '460507002308',
    projectId: 'energenius-56431',
    storageBucket: 'energenius-56431.firebasestorage.app',
    iosBundleId: 'com.example.energenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC10xxAzpPklDeYmwsIoqupWnhanDnjUhk',
    appId: '1:460507002308:web:1fe8f3888e315962c4e091',
    messagingSenderId: '460507002308',
    projectId: 'energenius-56431',
    authDomain: 'energenius-56431.firebaseapp.com',
    storageBucket: 'energenius-56431.firebasestorage.app',
    measurementId: 'G-5EBC7L8ZKS',
  );
}
